export const GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST' = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS' = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED: 'GET_PRODUCTS_FAILED' = 'GET_PRODUCTS_FAILED';

export const INCREASE_INGREDIENT: 'INCREASE_INGREDIENT' = 'INCREASE_INGREDIENT';
export const DECREASE_INGREDIENT: 'DECREASE_INGREDIENT' = 'DECREASE_INGREDIENT';
export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const ADD_INGREDIENTS: 'ADD_INGREDIENTS' = 'ADD_INGREDIENTS';
export const UPDATE_CONSTRUCTOR: 'UPDATE_CONSTRUCTOR' = 'UPDATE_CONSTRUCTOR';

export const CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST' = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS' = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED' = 'CREATE_ORDER_FAILED';

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';

export const GET_USER_ORDER_REQUEST: 'GET_USER_ORDER_REQUEST' = 'GET_USER_ORDER_REQUEST';
export const GET_USER_ORDER_SUCCESS: 'GET_USER_ORDER_SUCCESS' = 'GET_USER_ORDER_SUCCESS';
export const GET_USER_ORDER_FAILED: 'GET_USER_ORDER_FAILED' = 'GET_USER_ORDER_FAILED';